# Generated by Django 4.2.6 on 2024-01-28 11:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0002_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fee', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('national_code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_national_code', message='must be 10         digit', regex='^\\d{10}$')])),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(regex='(\\+98|0)?(9\\d{9})')])),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='appointment.doctor')),
            ],
        ),
    ]
